// hecke_cutters.m -- Hecke data for the matched Hilbert newforms (torsion-type mod-l reps).
// For each match: heckefield_<label> (a generator of the Hecke field, in Q[y]) and
// cutters_<label> = list of < prime ideal P of O_K, minpoly of a_P over Q >.
// Each block is self-contained (re-declares its field K<a> = Q(sqrt d), OK).
// Generated by emit_cutters.m; grows as sweep.m confirms matches.
//   Load with:  load "hecke_cutters.m";
//
// SCOPE: this file holds the 4 explicitly-identified forms (881_1/_2, 14303_1/_2; see
// results_torsion_hmf.md sec 4a). The full sweep matched 36/39 curves via the
// kernel-intersection method (kernel_torsion.m, results sec 4c), but that method yields a
// match CERTIFICATE (1-dim surviving mod-l eigenspace + control), NOT the char-0 eigenform
// -- so it produces no Hecke cutters. Adding cutters for the other 32 requires isolating
// each surviving eigenform (a follow-up computation); those blocks are intentionally absent
// here rather than fabricated.
Qy<y> := PolynomialRing(Rationals());     // y generates each Hecke field

// ---- 881.1  (F=Q(sqrt2), l=13; level norm 7048 = p2^3 * (prime-to-2 cond); orbit dim 18) ----
K<a> := QuadraticField(2); OK := Integers(K);   // self-contained: a = sqrt(2)
//      Hecke field: deg 18, disc 4253638350933629270399976706278872, Galois 18T0; not in LMFDB (large degree/disc)
heckefield_881_1 := y^18 - 54*y^16 - 6*y^15 + 1124*y^14 + 184*y^13 - 11538*y^12 - 2264*y^11 + 61687*y^10 + 13681*y^9 - 166924*y^8 - 35569*y^7 + 203946*y^6 + 26001*y^5 - 95812*y^4 - 10226*y^3 + 12624*y^2 + 2360*y - 16;
cutters_881_1 := [
  < ideal<OK | 3>, y^18 + 17*y^17 + 74*y^16 - 245*y^15 - 2532*y^14 - 1981*y^13 + 26272*y^12 + 51570*y^11 - 117427*y^10 - 345154*y^9 + 187821*y^8 + 1035589*y^7 + 216747*y^6 - 1366380*y^5 - 969569*y^4 + 442423*y^3 + 699359*y^2 + 251552*y + 27232 >,   // N(P) = 9
  < ideal<OK | 5>, y^18 + 33*y^17 + 319*y^16 - 1162*y^15 - 43547*y^14 - 260171*y^13 + 469115*y^12 + 12033929*y^11 + 44501109*y^10 - 56316999*y^9 - 852721809*y^8 - 2067056351*y^7 + 607748975*y^6 + 10349900301*y^5 + 12588696758*y^4 - 8439753640*y^3 - 24066987640*y^2 - 8013182592*y + 4208944064 >,   // N(P) = 25
  < ideal<OK | 2*a - 1>, y^18 - 54*y^16 - 6*y^15 + 1124*y^14 + 184*y^13 - 11538*y^12 - 2264*y^11 + 61687*y^10 + 13681*y^9 - 166924*y^8 - 35569*y^7 + 203946*y^6 + 26001*y^5 - 95812*y^4 - 10226*y^3 + 12624*y^2 + 2360*y - 16 >,   // N(P) = 7
  < ideal<OK | 2*a + 1>, y^18 + 8*y^17 - 21*y^16 - 304*y^15 - 233*y^14 + 3535*y^13 + 6267*y^12 - 17981*y^11 - 44980*y^10 + 40516*y^9 + 150365*y^8 - 20005*y^7 - 252439*y^6 - 70433*y^5 + 196619*y^4 + 114585*y^3 - 45655*y^2 - 49824*y - 10368 >,   // N(P) = 7
  < ideal<OK | 11>, y^18 + 27*y^17 - 487*y^16 - 18739*y^15 + 4747*y^14 + 4107291*y^13 + 22532242*y^12 - 317833147*y^11 - 2765513587*y^10 + 9051619144*y^9 + 127688119082*y^8 - 18325224776*y^7 - 2611261456546*y^6 - 2960865341641*y^5 + 22737939261662*y^4 + 40019962056332*y^3 - 56249965840480*y^2 - 133054870257792*y - 58651454037024 >,   // N(P) = 121
  < ideal<OK | 13>, y^18 + 73*y^17 + 1070*y^16 - 43475*y^15 - 1443157*y^14 - 151620*y^13 + 484029190*y^12 + 4715556014*y^11 - 53377199272*y^10 - 1080484020257*y^9 - 1193131166023*y^8 + 83002564637363*y^7 + 524656100649275*y^6 - 1128621069617603*y^5 - 21911135202863470*y^4 - 68017735219054844*y^3 + 26259192645059072*y^2 + 461590316652796032*y + 599871255543931104 >,   // N(P) = 169
];


// ---- 881.2  (F=Q(sqrt2), l=13; level norm 7048 = p2^3 * (prime-to-2 cond); orbit dim 18) ----
K<a> := QuadraticField(2); OK := Integers(K);   // self-contained: a = sqrt(2)
//      Hecke field: deg 18, disc 4253638350933629270399976706278872, Galois 18T0; not in LMFDB (large degree/disc)
heckefield_881_2 := y^18 + 8*y^17 - 21*y^16 - 304*y^15 - 233*y^14 + 3535*y^13 + 6267*y^12 - 17981*y^11 - 44980*y^10 + 40516*y^9 + 150365*y^8 - 20005*y^7 - 252439*y^6 - 70433*y^5 + 196619*y^4 + 114585*y^3 - 45655*y^2 - 49824*y - 10368;
cutters_881_2 := [
  < ideal<OK | 3>, y^18 + 17*y^17 + 74*y^16 - 245*y^15 - 2532*y^14 - 1981*y^13 + 26272*y^12 + 51570*y^11 - 117427*y^10 - 345154*y^9 + 187821*y^8 + 1035589*y^7 + 216747*y^6 - 1366380*y^5 - 969569*y^4 + 442423*y^3 + 699359*y^2 + 251552*y + 27232 >,   // N(P) = 9
  < ideal<OK | 5>, y^18 + 33*y^17 + 319*y^16 - 1162*y^15 - 43547*y^14 - 260171*y^13 + 469115*y^12 + 12033929*y^11 + 44501109*y^10 - 56316999*y^9 - 852721809*y^8 - 2067056351*y^7 + 607748975*y^6 + 10349900301*y^5 + 12588696758*y^4 - 8439753640*y^3 - 24066987640*y^2 - 8013182592*y + 4208944064 >,   // N(P) = 25
  < ideal<OK | -2*a + 1>, y^18 + 8*y^17 - 21*y^16 - 304*y^15 - 233*y^14 + 3535*y^13 + 6267*y^12 - 17981*y^11 - 44980*y^10 + 40516*y^9 + 150365*y^8 - 20005*y^7 - 252439*y^6 - 70433*y^5 + 196619*y^4 + 114585*y^3 - 45655*y^2 - 49824*y - 10368 >,   // N(P) = 7
  < ideal<OK | -2*a - 1>, y^18 - 54*y^16 - 6*y^15 + 1124*y^14 + 184*y^13 - 11538*y^12 - 2264*y^11 + 61687*y^10 + 13681*y^9 - 166924*y^8 - 35569*y^7 + 203946*y^6 + 26001*y^5 - 95812*y^4 - 10226*y^3 + 12624*y^2 + 2360*y - 16 >,   // N(P) = 7
  < ideal<OK | 11>, y^18 + 27*y^17 - 487*y^16 - 18739*y^15 + 4747*y^14 + 4107291*y^13 + 22532242*y^12 - 317833147*y^11 - 2765513587*y^10 + 9051619144*y^9 + 127688119082*y^8 - 18325224776*y^7 - 2611261456546*y^6 - 2960865341641*y^5 + 22737939261662*y^4 + 40019962056332*y^3 - 56249965840480*y^2 - 133054870257792*y - 58651454037024 >,   // N(P) = 121
  < ideal<OK | 13>, y^18 + 73*y^17 + 1070*y^16 - 43475*y^15 - 1443157*y^14 - 151620*y^13 + 484029190*y^12 + 4715556014*y^11 - 53377199272*y^10 - 1080484020257*y^9 - 1193131166023*y^8 + 83002564637363*y^7 + 524656100649275*y^6 - 1128621069617603*y^5 - 21911135202863470*y^4 - 68017735219054844*y^3 + 26259192645059072*y^2 + 461590316652796032*y + 599871255543931104 >,   // N(P) = 169
];


// ---- 14303.1  (F=Q(sqrt2), l=11; level norm 14303 = p2^0 * (prime-to-2 cond); orbit dim 5) ----
K<a> := QuadraticField(2); OK := Integers(K);   // self-contained: a = sqrt(2)
//      Hecke field: deg 5, disc 14641, Galois 5T1; try LMFDB nf disc 14641 deg 5
heckefield_14303_1 := y^5 - 2*y^4 - 5*y^3 + 13*y^2 - 7*y + 1;
cutters_14303_1 := [
  < ideal<OK | a>, y^5 - 2*y^4 - 5*y^3 + 13*y^2 - 7*y + 1 >,   // N(P) = 2
  < ideal<OK | 3>, y^5 + y^4 - 15*y^3 - 14*y^2 + 3*y + 1 >,   // N(P) = 9
  < ideal<OK | 5>, y^5 - 4*y^4 - 75*y^3 + 170*y^2 + 1010*y + 439 >,   // N(P) = 25
  < ideal<OK | 2*a - 1>, y^5 - 5*y^4 - 23*y^3 + 122*y^2 + 115*y - 683 >,   // N(P) = 7
  < ideal<OK | 2*a + 1>, y^5 - 33*y^3 + 242*y + 121 >,   // N(P) = 7
  < ideal<OK | 11>, y^5 + 9*y^4 - 335*y^3 - 2088*y^2 + 23665*y + 30097 >,   // N(P) = 121
];


// ---- 14303.2  (F=Q(sqrt2), l=11; level norm 14303 = p2^0 * (prime-to-2 cond); orbit dim 5) ----
K<a> := QuadraticField(2); OK := Integers(K);   // self-contained: a = sqrt(2)
//      Hecke field: deg 5, disc 14641, Galois 5T1; try LMFDB nf disc 14641 deg 5
heckefield_14303_2 := y^5 - 2*y^4 - 5*y^3 + 13*y^2 - 7*y + 1;
cutters_14303_2 := [
  < ideal<OK | -a>, y^5 - 2*y^4 - 5*y^3 + 13*y^2 - 7*y + 1 >,   // N(P) = 2
  < ideal<OK | 3>, y^5 + y^4 - 15*y^3 - 14*y^2 + 3*y + 1 >,   // N(P) = 9
  < ideal<OK | 5>, y^5 - 4*y^4 - 75*y^3 + 170*y^2 + 1010*y + 439 >,   // N(P) = 25
  < ideal<OK | -2*a + 1>, y^5 - 33*y^3 + 242*y + 121 >,   // N(P) = 7
  < ideal<OK | -2*a - 1>, y^5 - 5*y^4 - 23*y^3 + 122*y^2 + 115*y - 683 >,   // N(P) = 7
  < ideal<OK | 11>, y^5 + 9*y^4 - 335*y^3 - 2088*y^2 + 23665*y + 30097 >,   // N(P) = 121
];

